# Hexo Configuration
## Docs: http://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Grapher Docs
subtitle:
description: Documentation for grapher
author: Theodor Diaconu
language: en
timezone:

apis:
  ga: UA-40568040-9
  docsearch:
    apiKey: c6162b5842b0dc5f7af8c186fff8f5bb
    indexName: grapher

versions:
  - '1.1.0'

sidebar_categories:
  null:
    - index
  Guide:
    - guide/links
    - guide/query
    - guide/exposure
    - guide/namedQuery
  Packages:
    - packages/live
    - packages/boilerplate

github_repo: 'cult-of-coders/grapher-docs'
content_root: 'source'

# themeing
favicon: '../images/favicon.png'

logo:
  nav_mobile: '../images/logo.png'
  url: 'http://www.cultofcoders.com'
  title: 'Grapher'
  subtitle: ''

nav_links:
  'GitHub':
    url: https://github.com/cult-of-coders/grapher
    target: _new
  'Test Live':
    url: http://grapher-live.cultofcoders.com/grapher
    target: _new

social_links:
  github: 'https://github.com/cult-of-coders/grapher'
  twitter: '@culotfcoders'

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://grapher.cultofcoders.com
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: true
  tab_replace:

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: http://hexo.io/plugins/
## Themes: http://hexo.io/themes/
theme: meteor
marked:
  breaks: false

# Deployment
## Docs: http://hexo.io/docs/deployment.html
deploy:
  type: s3
